openapi: 3.1.1
info:
  version: 1.0.0
  title: The Core API description
  description: The Core API description of the Mairie360 Core API
  contact:
    name: Clément Antoine XAVIER
    url: https://github.com/marie360/core-api-description
    email: clement-antoine.xavier@epitech.eu
  license: 
    name: MIT License
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://api.development.mairie360.fr
    description: Development server
tags:
  - name: Modules
    description: Module operations
paths:
  /modules:
    $ref: "./resources/modules.yaml"
  /modules/{module_id}:
    $ref: "./resources/module.yaml"
  /users:
    $ref: "./resources/users.yaml"
  /users/{user_id}:
    $ref: "./resources/user.yaml"
  /sessions:
    $ref: "./resources/sessions.yaml"
  /sessions/{session_id}:
    $ref: "./resources/session.yaml"
  /users/{user_id}/password:
    $ref: "./resources/password.yaml"
  /roles:
    $ref: "./resources/roles.yaml"
  /roles/{role_id}:
    $ref: "./resources/role.yaml"
  /permissions:
    $ref: "./resources/permissions.yaml"
  /permissions/{permission_id}:
    $ref: "./resources/permission.yaml"
  /resources:
    $ref: "./resources/resources.yaml"
  /resources/{resource_id}:
    $ref: "./resources/resource.yaml"
components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"